### ISSUE TITLE
Viacero textov nie je dobre zarovnaných / nezmestí sa

### ISSUE THREAD

**Issue by Zajozor** [cedeerwe/brutalna-akademia#1]
![image](https://user-images.githubusercontent.com/1835434/61594911-20f66f00-abf1-11e9-9aa6-ff6782ba6d63.png)
![image](https://user-images.githubusercontent.com/1835434/61594912-25bb2300-abf1-11e9-801a-2a817d2ccdae.png)
![image](https://user-images.githubusercontent.com/1835434/61594920-2f448b00-abf1-11e9-846f-fa3584a10660.png)
![image](https://user-images.githubusercontent.com/1835434/61594939-48e5d280-abf1-11e9-9e9f-619dd69bcd24.png)

a dalsie rozne. Zrejme len nejaka blbost co treba poprepisovat.

**Comment by cedeerwe** [comment]
@Zajozor az teraz som si vsimol, ze si mi otvoril issues. Nastavim si notifikacie.

O tomto viem, bohuzial. Pointa je, ze collapsible headings extension nieco pokazi s mathjax, ked su sekcie collapsed. Snazil som sa to debuggovat, ale nepodarilo sa. Otvoril som [issue](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1435) priamo v `nbextensions`, ale vyzera, ze ich nestihaju moc riesit. Ak by ta nieco napadlo, potesim sa

**Comment by cedeerwe** [comment]
Prestrukturoval som notebook - namiesto collapsible headings som pouzil exercise2. Nema to sice nested schovane veci, ale myslim, ze to staci aj takto. Matika je pekne a to je omnoho dolezitejsie.
