### ISSUE TITLE
Pripomienky k minciam

### ISSUE THREAD

**Issue by cedeerwe** [cedeerwe/brutalna-akademia#3]
Zoznam pripomienok
- [x] adresovanie citatela ty vs. vy
- [x] odstavec za navodnymi ulohami o tom, aby si skusili premysliet vysledok
- [ ] vyznacovanie klucovych slov, referencie na ne

**Comment by Zajozor** [comment]
![image](https://user-images.githubusercontent.com/1835434/65605081-c68add80-dfa8-11e9-8587-ffa85c1a9cd7.png)
Tu aj napisat ze co hra proti comu, nie ze "ako minule", nech to nemusim hladat.

**Comment by Zajozor** [comment]
Tento graf je velmi tesne scrollovaci.. ak by sa ho podarilo trocha zmensit bol by lepsi UX
![image](https://user-images.githubusercontent.com/1835434/65605198-fc2fc680-dfa8-11e9-95a8-4a5e951a907b.png)

**Comment by Zajozor** [comment]
Prislo by mi cool asi respektovat tu hranicu na koniec riadku ked uz tam je, takto to vyzera smiesne 
![image](https://user-images.githubusercontent.com/1835434/65605709-e242b380-dfa9-11e9-80b2-cd7122db8f9b.png)

**Comment by Zajozor** [comment]
Opinion based thing, ale preco tie pismena pribudaju vsade odzadu ?
![image](https://user-images.githubusercontent.com/1835434/65605798-01414580-dfaa-11e9-9ef2-bda0fe6456df.png)

Ja by som cakal, ze ked som v stave `__` a hodim hlavu budem v stave `H_` nie `_H` 🤔 
ale mozno som len missol nejaku cast vdaka ktorej to dava zmysel..

**Comment by Zajozor** [comment]
Viac by sa mi robilo robit odhady rychlo do tej vety (akoze rychle neni nutne zle)
![image](https://user-images.githubusercontent.com/1835434/65606136-9e03e300-dfaa-11e9-8151-9f554b4b3406.png)

**Comment by Zajozor** [comment]
Switch na Colab je urcite krok vpred, fajne to je, ale este by som znizil nesting..
ked si to citam, trocha ma otravuje vsetko rozklikavat,
podla mna napriklad tuto

![image](https://user-images.githubusercontent.com/1835434/65606203-bd9b0b80-dfaa-11e9-908d-d8c57bcd3361.png)

by pod Ulohou 1 mohli byt ze napoveda 1, napoveda 2, riesenie, alebo tak..
Pripadne ked si kliknem riesenie, tak v nom mozu byt niektore veci otvorene.. napr. odhad?
Neviem, chapem, ze je fajn tie veci skryvat, ale narusa mi to celkom dost focus ked to musim otvarat, taky je moj pocit..

**Comment by cedeerwe** [comment]
> Opinion based thing, ale preco tie pismena pribudaju vsade odzadu ?

Idea je, že to tak potom aj programuješ. Pamätáš si posledné tri hody, a keď hodíš v stave `__` hlavu, tak budeš mať uložené `_H`. Možno je to menej intuitívne, ale ľahšie sa mi s tým takto pracovalo.

Predstav si, že by si mal dĺžku 3 a máš sekvenciu `HHZ`. Ak teraz hodíš hlavu, budeš mať `HZH`. Ak hodíš Zase hlavu, budeš mať `ZHH`. Deje sa presne taký presun, ako zobrazujú tie medzery na začiatku, nie na konci. Preto mi to tak prišlo rozumnejšie.

Asi to ale nie je major vec a netreba to až tak riešiť.

**Comment by cedeerwe** [comment]
> Switch na Colab je urcite krok vpred, fajne to je, ale este by som znizil nesting..

Ten nesting by som aj ja spravil rád možno menej, ale ešte som nepochopil plnú mágiu synchronizácie s Githubom, aby mi zachovávalo taký nesting, ako chcem. Napríklad teraz som nechal viacero vecí pod úlohou otvorené, ale v mastrovi sa nič nezmenilo.

Beriem na vedomie a časom poriešim.
