### ISSUE TITLE
detaily v  05 odhadovanie

### ISSUE THREAD

**Issue by Zajozor** [cedeerwe/brutalna-akademia#5]
![image](https://user-images.githubusercontent.com/1835434/72202601-cc2a0780-3461-11ea-9ce8-532993cf150e.png)
tu poznamku by som presunul do zatvorky k bodu dva.

![image](https://user-images.githubusercontent.com/1835434/72202637-393d9d00-3462-11ea-8d23-022ff969912e.png)
scenarov je lubozvucnejsie nez scenarii

![image](https://user-images.githubusercontent.com/1835434/72202651-6db15900-3462-11ea-9881-50763e483391.png)
doplnil by som "o intervalovom odhade (resp. intervale spolahlivosti) sa mozte docitat tu"
**interval spolahlivosti** som v zivote pocul celkom vela krat, intervalovy odhad az tak nie

ten ipynb je nejak v zlom priecinku nie :D ? 
![image](https://user-images.githubusercontent.com/1835434/72202725-2081b700-3463-11ea-9440-3dddf9e37851.png)

Do domacej ulohy by som tiez doplnil, ze nas asi zaujima bodovy odhad, lebo ked idem stavat obchodne centrum, nechcem interval parkovacich miest. Alebo praveze nejaky interval spolahlivosti a postavim pre istotu viac tych 5m? mozno je to na diskusiu no

**Comment by cedeerwe** [comment]
drobnosti som doplnil, presuniem to pravdaze do spravneho priecinka (diky :D) a ten posledny bod by som nechal na diskusiu medzi nimi, co si myslia, ze moze byt vhodnejsie.
